version: "3.9"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        depends_on:
            - php
            # - mysql
        networks:
            - laravel

    # mysql:
    #     image: mysql:latest
    #     container_name: mysql
    #     restart: unless-stopped
    #     tty: true
    #     ports:
    #         - "4306:3306"
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_DATABASE: homestead
    #         MYSQL_USER: homestead
    #         MYSQL_PASSWORD: secret
    #         MYSQL_ROOT_PASSWORD: secret
    #         SERVICE_TAGS: dev
    #     networks:
    #         - laravel

    php:
        image: php:7.4-fpm-alpine
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
